# Generated by Django 3.0.6 on 2020-05-27 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Category', verbose_name='所属板块'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_modify',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='priorty',
            field=models.IntegerField(default=1000, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '隐藏')], default='published', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, to='bbs.UserProfile', verbose_name='版主'),
        ),
        migrations.AddField(
            model_name='category',
            name='brief',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='板块名称'),
        ),
        migrations.AddField(
            model_name='category',
            name='position_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='顶部展示的位置'),
        ),
        migrations.AddField(
            model_name='category',
            name='set_as_top_menu',
            field=models.BooleanField(default=False, verbose_name='是否将此板块设置在页面顶部'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Article', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.IntegerField(choices=[(1, '评论'), (2, '点赞')], default=1, verbose_name='评论类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_children', to='bbs.Comment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile', verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='', verbose_name='头像', width_field=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理Gjango内部的用户'),
        ),
    ]
