# Generated by Django 3.0.6 on 2020-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200527_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(blank=True, to='bbs.UserProfile', verbose_name='版主'),
        ),
    ]
